[package]
name = "ta-ko-ho/understand-medical-year"
version = "0.1.0"
description = "wasmer-tests/wasmer-edge-astro-sample website"

[dependencies]
"wasmer/static-web-server" = "*"

[fs]
public = "dist"
